### ISSUE TITLE
docker image, network issues?

### ISSUE THREAD

**Issue by shuffl3r** [isaudits/docker-deathstar#1]
interesting project - how would you go about configuring the network for responder to work when this is pulled as a docker image?

**Comment by mcjon3z** [comment]
On Linux, running the image with net=host flag (see deathstar.sh) bridges the networking to the host interface. On OSX, the responder piece is not fully functional however I have not fully determined whether this is due to the NAT implementation of the OSX docker vm or a port conflict. 

On my OSX machine, I run this container on a kali Linux vm that has a bridged network adapter and responder works just fine.

**Comment by jshuffler** [comment]
If only I viewed that file XD.  Adding --net=host solved my issue!  Thank you for the prompt response!

**Comment by shuffl3r** [comment]
Any future plans to incorporate something like Gladius (https://github.com/praetorian-inc/gladius) into the project?

Would be a good way to leverage weak NTLMv2 hashes.

**Comment by mcjon3z** [comment]
That is an idea but I don't personally use it so I'm not intimately familiar with how it works. I run relays first and then go back and run Responder natively to grab hashes if the network is not vulnerable to relay. If it is, there's not much point in cracking the hashes. 

Just in glancing at the Gladius code, I can see there potentially being some issues:

- It uses Hashcat for the cracking which would introduce complexities trying to run inside of Docker because of the GPU. From what I understand, GPU cracking would only work in an instance where you were running Docker natively on a Linux box as opposed to inside a VM (or inside an OSX/Windows Docker instance which inherently puts Docker in a VM). I believe it would also require the docker image for hashcat to have the correct GPU drivers for whatever host you were running on.

- The Responder config in this project disables the SMB and HTTP modules in Responder so that NTLMRelayX can pick them up and hit them with the Empire shellcode. In my experience, running it in this method results in Responder not actually catching any hashes. The Responder config is modified at build time, so you'd have to modify that to set the config up based on which attack scenario you are running.

May be something to consider for another standalone docker project...
